<Project InitialTargets="ValidateGamePath">
  <!--
    Add a GameFolder.props file to the solution to set your game path:

    <Project>
      <PropertyGroup>
        <GameFolder>C:\Program Files (x86)\Steam\steamapps\common\GTFO</GameFolder>
      </PropertyGroup>
    </Project>
  -->

  <Import Project="$(MSBuildThisFileDirectory)/GameFolder.props" Condition="Exists('$(MSBuildThisFileDirectory)/GameFolder.props')" />
  <Target Name="ValidateGamePath">
    <Error Text="The GameFolder property must be set to the GTFO game folder." Condition="'$(GameFolder)' == '' or !Exists('$(GameFolder)')" />
  </Target>

  <PropertyGroup>
    <BIELibsFolder>$(GameFolder)/BepInEx/core</BIELibsFolder>
    <MonoLibsFolder>$(GameFolder)/dotnet/corlib</MonoLibsFolder>
    <UnhollowedLibsFolder>$(GameFolder)/BepInEx/interop</UnhollowedLibsFolder>
    <PluginLibFolder>$(GameFolder)/Plugins</PluginLibFolder>
  </PropertyGroup>

  <!-- Twitch Libs -->
  <ItemGroup>
    <!--Reference Include="../_twitchlib_2.0/*.dll"/-->
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(PluginLibFolder)/*.dll" Private="false" />
  </ItemGroup>

  <!-- BepInEx libs -->
  <ItemGroup>
    <Reference Include="$(BIELibsFolder)/BepInEx.*.dll" Private="false" />
    <Reference Include="$(BIELibsFolder)/0Harmony.dll" Private="false" />
    <Reference Include="$(BIELibsFolder)/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="$(MonoLibsFolder)\..\System.Private.CoreLib.dll" Private="false" />
  </ItemGroup>

  <!-- BepInEx mono libs -->
  <ItemGroup>
    <Reference Include="$(MonoLibsFolder)/*.dll" Private="false" />
    <Reference Remove="$(MonoLibsFolder)\msquic.dll" />
    <Reference Remove="$(MonoLibsFolder)\System.IO.Compression.Native.dll" />
  </ItemGroup>

  <!-- Unhollowed assemblies -->
  <ItemGroup>
    <Reference Include="$(UnhollowedLibsFolder)/*.dll" Private="false" />
    <Reference Remove="$(UnhollowedLibsFolder)/netstandard.dll" />
    <Reference Remove="$(UnhollowedLibsFolder)/mscorlib.dll" />
    <Reference Remove="$(UnhollowedLibsFolder)/Newtonsoft.Json.dll" />
  </ItemGroup>
</Project>
