<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Dependencies.props" />
  
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Assets\TwitchDice.bnk" />
    <None Remove="Assets\VineBOOMSFX.bnk" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Assets\Bundle\snowman" />
    <EmbeddedResource Include="Assets\TwitchDice.bnk" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.5" />
    <PackageReference Include="TwitchLib" Version="3.2.0" />
  </ItemGroup>
</Project>
