<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Dependencies.props" />
  
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)bin\Debug\netstandard2.1\$(ProjectName).dll&quot; &quot;C:\Users\Dak\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\TwitchDice\BepInEx\plugins\TwitchDice&quot; /Y" />
  </Target>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.5" />
    <PackageReference Include="TwitchLib" Version="3.2.0" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Twitch\Events\D6\" />
    <Folder Include="Twitch\Events\D8\" />
    <Folder Include="Twitch\Events\D12\" />
    <Folder Include="Twitch\Events\D20\" />
    <Folder Include="Twitch\Events\D50\" />
  </ItemGroup>
</Project>
